### ISSUE TITLE
Documentation incorrectly states that nil is false

### ISSUE THREAD

**Issue by lzfelix** [clojuredocs/guides#233]
I am learning Clojure through the docs and on the [Truthiness](http://clojure-doc.org/articles/tutorials/introduction.html#truthiness) section of the "Introduction to Clojure" it reads:

> Clojure takes a very simple approach here: `nil` and `false` are falsey; everything else is truthy.

But the [documentation for `if`](http://clojuredocs.org/clojure.core/false%3F) clearly states that `nil` is not false.

**Comment by seancorfield** [comment]
You linked to the documentation for `false?`, not `if`. The `false?` function tests if its argument is `false` (not "falsey").

If you look at the documentation for `if` -- http://clojure.org/reference/special_forms#if -- you'll see it treats both `nil` and `false` as "falsey", and everything else as "truthy".

The section on Truthiness here reflects that.

Does that help?

**Comment by lzfelix** [comment]
Yes, it helps.
Indeed the link is wrong, my apologies. At that time I thought is `(false? nil)` would evaluate to `true`, since `nil` is "falsey".

**Comment by seancorfield** [comment]
There's also a `true?` predicate for testing if a value is `true` rather than just "truthy". Mostly in Clojure you only care about "truthy" or "falsey", especially when relying on nil-punning (that `nil` is "falsey" and non-`nil` is "truthy"), but sometimes you care about actual Boolean values (since `false` is a non-`nil` value, but it isn't "truthy"). It can seem strange when you first start learning Clojure because almost all other languages do things differently, but it will soon become clear why this is a useful idiom and then you'll just get used to it. Welcome to Clojure!
