### ISSUE TITLE
Changes sync'd to the server are not showing up

### ISSUE THREAD

**Issue by seancorfield** [clojuredocs/guides#259]
I made a small change to the concurrency and parallelism page in #258 and rebuilt the site and rsync'd it up to the server -- last week -- but the updated page still isn't being served. I validated the changed HTML file on the server. I thought maybe it was just a cache or CDN issue but the old page is still being served several days later.

Did the rsync location change? Or is there some other part of the process that changed?

**Comment by michaelklishin** [comment]
It's a bit complicated. The current machine that serves the site is in a limbo state: it's been originally provisioned in 2012 and upgraded. Unfortunately due to certain IaaS provider changes it's no longer possible to upgrade the distribution and an incomplete update messed up all `apt-get` features and possibly a few packages. Nginx is still running 

So I provisioned a new machine but yet to finish the move.

**Comment by seancorfield** [comment]
Ah, yes, I vaguely remember you mentioning this -- and a discussion of potentially moving the Guides to GitHub pages (which is how I publish my blog @ corfield.org). Let me know if there's anything I can do to help!

**Comment by seancorfield** [comment]
@michaelklishin At this point, we're three years past the last update. Why don't we move this to clojuredocs.github.io as a repo on a source branch and just publish it to GitHub pages as the default branch (which is how I do I my blog and a few other sites)?

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.

**Comment by seancorfield** [comment]
I'm am resurrecting this site at https://clojure-doc.github.io so feel free to recreate this issue at https://github.com/clojure-doc/clojure-doc.github.io/issues or submit a PR https://github.com/clojure-doc/clojure-doc.github.io/pulls
