### ISSUE TITLE
Missing book on Clojure

### ISSUE THREAD

**Issue by turbopape** [clojuredocs/guides#269]
Hello Guys, I've seen you omitted mentioning my book on Clojure:
[Clojure Data Structures and Algorithms Cookbook](https://www.packtpub.com/application-development/clojure-data-structures-and-algorithms-cookbook)
Thank you :)

**Comment by seancorfield** [comment]
Feel free to submit a PR but due to infrastructure problems, the website has not been updated since 2018. /cc @michaelklishin

**Comment by seancorfield** [comment]
I'm am resurrecting this site at https://clojure-doc.github.io so feel free to recreate this issue at https://github.com/clojure-doc/clojure-doc.github.io/issues or submit a PR https://github.com/clojure-doc/clojure-doc.github.io/pulls

**Comment by seancorfield** [comment]
@turbopape After careful review, I have decided to defer to https://clojure.org/community/books instead of trying to duplicate a list of books. Feel free to create an issue at https://github.com/clojure/clojure-site or open a pull request (but note the https://github.com/clojure/clojure-site/blob/master/CONTRIBUTING.md guidelines).
