### ISSUE TITLE
Docs published in concurrency and parallelism section on clojure-doc.org not reflecting updates seen in git history

### ISSUE THREAD

**Issue by Zak-Kent** [clojuredocs/guides#271]
The [futures](http://clojure-doc.org/articles/language/concurrency_and_parallelism.html#futures) section of the concurrency and parallelism docs have a section stating that futures are evaluated in a fixed sized thread pool (via **clojure.core/send**). In the history I found this [commit](https://github.com/clojuredocs/guides/commit/5cf8c0c4e0ab69264c0ea66d899f414f21be9a5e) which corrects this and states that futures are evaluated using an unbounded, cached thread pool (via **clojure.core/send-off**) . I'm wondering if the changes weren't published correctly for some reason.

**Comment by seancorfield** [comment]
A lot of changes to the repo have not been published. Last time I spoke to the maintainer of the server, he said there were problems with the infrastructure that were preventing the site being republished to the server. See issue #259 for more background (so we're coming up on two years since the server got updated).

**Comment by seancorfield** [comment]
I'm am resurrecting this site at https://clojure-doc.github.io which should allow us to publish updates regularly.
